### ISSUE TITLE
POST w/ empty data causes exception

### ISSUE THREAD

**Issue by dismay** [reactphp/http#63]
Hi, POST w/ empty data causes exception w/ message: "Undefined index: content-type":

```
POST /path/to/endpoint HTTP/1.1
Host: example.com
Connection: keep-alive
Content-Length: 0  <-- POST data is empty, XMLHttpRequest set it to 0
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/javascript, */*; q=0.01
Origin: http://example2.com/
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Referer: http://example2.com/test.html
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
```

Possible patch:

```
--- a/src/StreamingBodyParser/Factory.php
+++ b/src/StreamingBodyParser/Factory.php
@@ -16,7 +16,8 @@ class Factory
         $headers = array_change_key_case($headers, CASE_LOWER);

         if (
-            !isset($headers['content-type']) && !isset($headers['content-length'])
+            (!isset($headers['content-type']) && !isset($headers['content-length'])) ||
+            (isset($headers['content-length']) && $headers['content-length'] == 0)
         ) {
             return new NoBodyParser($request);
         }
```

Thanks

**Comment by clue** [comment]
Thanks for posting this. Which version are you testing this against? The current master branch does not contain a `StreamingBodyParser`.

**Comment by dismay** [comment]
ah, sorry, forgot to mention - it's streaming-multipart branch

**Comment by WyriHaximus** [comment]
Interesting, those lines shouldn't create that error as they are literally checking for the existence of those indexes. Do you have a full error including file a line or a stack trace?

**Comment by dismay** [comment]
ok, my fault - it's usual PHP Notice which was handled by custom error handler - in my case \yii\error\ErrorHandler that throws an Exception
Conserning the lines:

orig - http/src/StreamingBodyParser/Factory.php:
```
    public static function create(Request $request)
    {
        $headers = $request->getHeaders();
        $headers = array_change_key_case($headers, CASE_LOWER);

        if (
            !isset($headers['content-type']) && !isset($headers['content-length'])
        ) {
            return new NoBodyParser($request);
        }
        
>       $contentType = strtolower($headers['content-type']);
        ...
```

stack trace:
```
Undefined index: content-type
#0 /home/user/project/service/vendor/react-http/src/StreamingBodyParser/Factory.php(32): yii\\base\\ErrorHandler->handleError(8, \'Undefined index...\', \'/home/user/proj...\', 32, Array)
#1 /home/user/project/service/vendor/service-core/Application.php(320): React\\Http\\StreamingBodyParser\\Factory::create(Object(React\\Http\\Request))
#2 /home/user/project/service/vendor/service-core/Application.php(113): app\\modules\\core\\Application->hidrateRequestToYiiApp(Object(React\\Http\\Request))
#3 [internal function]: app\\modules\\core\\Application->app\\modules\\core\\{closure}(Object(React\\Http\\Request), Object(React\\Http\\Response))
#4 /home/user/project/service/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(65): call_user_func_array(Object(Closure), Array)
#5 /home/user/project/service/vendor/react-http/src/Server.php(61): Evenement\\EventEmitter->emit(\'request\', Array)
#6 /home/user/project/service/vendor/react-http/src/Server.php(27): React\\Http\\Server->handleRequest(Object(React\\Socket\\Connection), Object(React\\Http\\Request), \'\')
#7 [internal function]: React\\Http\\Server->React\\Http\\{closure}(Object(React\\Http\\Request), \'\')
#8 /home/user/project/service/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(65): call_user_func_array(Object(Closure), Array)
#9 /home/user/project/service/vendor/react-http/src/RequestParser.php(55): Evenement\\EventEmitter->emit(\'headers\', Array)
#10 [internal function]: React\\Http\\RequestParser->feed(\'POST /endpoint...\', Object(React\\Socket\\Connection))
#11 /home/user/project/service/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(65): call_user_func_array(Array, Array)
#12 /home/user/project/service/vendor/react/socket/src/Connection.php(15): Evenement\\EventEmitter->emit(\'data\', Array)
#13 [internal function]: React\\Socket\\Connection->handleData(Resource id #223, Object(React\\EventLoop\\ExtEventLoop))
#14 /home/user/project/service/vendor/react/event-loop/src/ExtEventLoop.php(319): call_user_func(Array, Resource id #223, Object(React\\EventLoop\\ExtEventLoop))
#15 [internal function]: React\\EventLoop\\ExtEventLoop->React\\EventLoop\\{closure}(Resource id #223, 2, NULL)
#16 /home/user/project/service/vendor/react/event-loop/src/ExtEventLoop.php(205): EventBase->loop(1)
#17 /home/user/project/service/vendor/service-core/Application.php(310): React\\EventLoop\\ExtEventLoop->run()
#18 /home/user/project/service/vendor/service-core/Application.php(139): app\\modules\\core\\Application->startLoop(Object(Closure))
#19 /home/user/project/service/vendor/service-core/Application.php(65): app\\modules\\core\\Application->runReactApp()
#20 /home/user/project/service/web/index.php(13): app\\modules\\core\\Application->run()
#21 {main}
```

The "if" does not work here because of missed 'content-type' header in the POST, then we have PHP Notice in next line and Exception in my case.
Btw I've just switched to use ExtEventLoop and found interesting line 205:
```
public function run()
{
   ...
            // @-suppression: https://github.com/reactphp/react/pull/234#discussion-diff-7759616R226
            @$this->eventBase->loop($flags);
        }
   ...
```
no error reporting for this notice and as result the request will never finish... Have to return default StreamSelectLoop back

**Comment by dismay** [comment]
@WyriHaximus is it enough for a fix? thanks

**Comment by WyriHaximus** [comment]
@dismay I'll push a fix to that branch later today

**Comment by WyriHaximus** [comment]
@dismay just pushed a fix and test for this case

**Comment by dismay** [comment]
@WyriHaximus hm.. wait, why RawBodyParser? Case is: POST has no body but has 'content-length: 0' header otherwise it will wait for a data, won't iit?
see example here https://jsfiddle.net/w2mmf0p4/ - just open devtool (F12) -> network tab -> filter XHR and press Run. 
Request headers will look like:
POST /echo/html/ HTTP/1.1
Host: fiddle.jshell.net
Connection: keep-alive
Content-Length: 0
Accept: */*
Origin: https://fiddle.jshell.net
X-Requested-With: XMLHttpRequest
User-Agent: XXXX
Referer: https://fiddle.jshell.net/_display/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-us

maybe better to use NoBodyParser in such case? thanks

**Comment by WyriHaximus** [comment]
So it still has a `content-length` and we respect that by using a `RawBodyParser` which will go until it worked the entire body length. (`NoBodyParser` is for when we can't detect the kind of body we're getting passed.) It isn't the factories responsibility to know about the size of the body, just to figure out and return the right body parser.

**Comment by dismay** [comment]
@WyriHaximus  ok, not a Factory responsibility but whom then? me or library?
It's the real case produced by jquery ajax call..
Let's see the following tests:
```
    public function testRequestNoContentType()
    {
        $data = "POST / HTTP/1.1\r\n";
        $data .= "Host: example.com:80\r\n";
        $data .= "Content-Length: 0\r\n";
        $data .= "\r\n";

        $io = new \React\Tests\Http\ServerStub();
        $server = new \React\Http\Server($io);
        $conn = new \React\Tests\Http\ConnectionStub();
        $io->emit('connection', array($conn));

        $requestHandled = false;

        $server->on('request', function ($request, $response) use (&$requestHandled) {
            $parser = \React\Http\StreamingBodyParser\Factory::create($request);
            \React\Http\StreamingBodyParser\BufferedSink::createPromise($parser)
                ->then(function ($result) use (&$requestHandled) {
                    $requestHandled = true;
                    // ...
                    // process to prepare response
                    // ...
                    var_dump('we won't be here ;(');
                });
        });

        $conn->emit('data', array($data));
        $this->assertEquals(false, $requestHandled);
    }

    public function testRequestNoContentTypeWithHeadersFix()
    {
        $data = "POST / HTTP/1.1\r\n";
        $data .= "Host: example.com:80\r\n";
        $data .= "Content-Length: 0\r\n";
        $data .= "\r\n";

        $io = new \React\Tests\Http\ServerStub();
        $server = new \React\Http\Server($io);
        $conn = new \React\Tests\Http\ConnectionStub();
        $io->emit('connection', array($conn));

        $requestHandled = false;

        $server->on('request', function ($request, $response) use (&$requestHandled) {
            // fix $headers via reflection o_O
            $headers = $request->getHeaders();

            if (!isset($headers['Content-Type']) &&
                isset($headers['Content-Length']) &&
                $headers['Content-Length'] == 0)
            {
                unset($headers['Content-Length']);
                $property = new \ReflectionProperty($request, 'headers');
                $property->setAccessible(true);
                $property->setValue($request, $headers);
            }

            $parser = \React\Http\StreamingBodyParser\Factory::create($request);
            \React\Http\StreamingBodyParser\BufferedSink::createPromise($parser)
                ->then(function ($result) use (&$requestHandled) {
                    $requestHandled = true;
                    // ...
                    // process to prepare response
                    // ...
                    var_dump('Hey, we are here!');
                });
        });

        $conn->emit('data', array($data));
        $this->assertEquals(true, $requestHandled);
    }
```
maybe you can suggest where can I fix the headers more elegant? or maybe RawBodyParser can detect the case w/ no data? thanks

**Comment by WyriHaximus** [comment]
Yup you found a neat little edge case there :+1: . Will be pushing a commit soon fixing it. Thanks!

As for responsibilties, the `Factory` is responsible to find out which parser to use, the `RawBodyParser` is responsible for parsing and emitting what content it finds, in its specific case emitting the full body once it reaches that length given by the `content-length` header, and it delegates that task to the `ContentLengthBufferedSink` which wasn't build with a zero content length in mind.

**Comment by clue** [comment]
Thanks for filing this ticket, I can assure you we're working hard on this :+1: 

This ticket currently targets an unstable development branch, so I've just filed #105 to keep track of the underlying feature request here. Please bear with us, we'll keep this ticket updated :+1:
